import type { DataTableRef, TableRowData } from './data-table';
import type { PendingChange, SortState } from '@/types/database';
import {
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Eye,
  FileText,
  Loader2,
  Plus,
} from 'lucide-react';
import { useCallback, useMemo, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { usePendingChanges } from '@/hooks/usePendingChanges';
import { useTableData } from '@/hooks/useTableData';
import { useConnectionStore } from '@/stores';
import { DataTable } from './data-table';
import { DiffPreview } from './DiffPreview';

export function TableView() {
  const { connection, selectedTable } = useConnectionStore();
  const dataTableRef = useRef<DataTableRef>(null);

  // Pagination state (local since TanStack Query handles the data)
  const [page, setPage] = useState(1);
  const [pageSize] = useState(100);
  const [sort, setSort] = useState<SortState | null>(null);
  const [grouping, setGrouping] = useState<string[]>([]);
  const [showDiffPreview, setShowDiffPreview] = useState(false);

  // Track the newly inserted row ID for auto-focus
  const [newRowId, setNewRowId] = useState<string | number | null>(null);

  // Find primary key column
  const primaryKeyColumn = selectedTable?.primaryKey[0];

  // Use TanStack DB hooks for data and changes
  const {
    rows,
    columns,
    totalRows,
    totalPages,
    isLoading,
    error,
    updateRow,
    insertRow,
    deleteRow,
    refetch,
  } = useTableData({
    connectionId: connection?.id || null,
    schema: selectedTable?.schema,
    table: selectedTable?.name || null,
    page,
    pageSize,
    sortColumn: sort?.column,
    sortDirection: sort?.direction,
    enabled: Boolean(connection && selectedTable),
    primaryKeyColumn,
  });

  const {
    changes: pendingChanges,
    hasChanges,
    changeCount,
  } = usePendingChanges({
    connectionId: connection?.id || null,
    schema: selectedTable?.schema,
    table: selectedTable?.name,
  });

  // Transform rows for DataTable display
  const displayRows = useMemo((): TableRowData[] => {
    return rows.map((row) => {
      const rowId = row.__rowId;
      const isNew = '__isNew' in row && row.__isNew;
      const isDeleted = '__isDeleted' in row && row.__isDeleted;

      // Find the corresponding pending change
      const change = pendingChanges.find((c) => c.rowId === rowId);

      return {
        ...row,
        __rowId: rowId,
        __isNew: isNew,
        __deleted: isDeleted,
        __change: change as PendingChange | undefined,
      } as TableRowData;
    });
  }, [rows, pendingChanges]);

  // Build changes map for DataTable
  const changesMap = useMemo(() => {
    const map = new Map<string | number, PendingChange>();
    pendingChanges.forEach((c) => map.set(c.rowId, c as PendingChange));
    return map;
  }, [pendingChanges]);

  // Handle page change
  const handlePageChange = useCallback((newPage: number) => {
    setPage(newPage);
  }, []);

  // Handle sort change from DataTable
  const handleSortChange = useCallback((newSort: SortState | null) => {
    setSort(newSort);
    setPage(1); // Reset to first page on sort change
  }, []);

  // Handle cell change from DataTable
  const handleCellChange = useCallback(
    (
      rowId: string | number,
      columnId: string,
      newValue: unknown,
      _oldValue: unknown
    ) => {
      updateRow(rowId, { [columnId]: newValue });
    },
    [updateRow]
  );

  // Handle row delete from DataTable
  const handleRowDelete = useCallback(
    (rowId: string | number) => {
      deleteRow(rowId);
    },
    [deleteRow]
  );

  // Handle adding a new row
  const handleAddRow = useCallback(() => {
    if (!selectedTable || selectedTable.type === 'view') return;

    // Initialize row with smart default values
    const newRow: Record<string, unknown> = {};
    columns.forEach((col) => {
      // Skip auto-increment columns (they'll be generated by the database)
      const type = col.type.toLowerCase();
      const isAutoIncrement =
        col.isPrimaryKey &&
        (type.includes('int') ||
          type === 'integer' ||
          col.defaultValue
            ?.toString()
            .toLowerCase()
            .includes('autoincrement') ||
          col.defaultValue?.toString().toLowerCase().includes('nextval'));

      if (isAutoIncrement) {
        // Leave auto-increment columns as null - database will handle it
        newRow[col.name] = null;
      } else if (col.defaultValue !== undefined && col.defaultValue !== null) {
        newRow[col.name] = col.defaultValue;
      } else {
        newRow[col.name] = null;
      }
    });

    const rowId = insertRow(newRow);
    setNewRowId(rowId);
  }, [selectedTable, columns, insertRow]);

  // Callback when DataTable has focused the new row
  const handleNewRowFocused = useCallback(() => {
    setNewRowId(null);
  }, []);

  // Handle successful change application
  const handleChangesApplied = useCallback(() => {
    setShowDiffPreview(false);
    refetch();
  }, [refetch]);

  if (!selectedTable) return null;

  return (
    <div className="flex h-full min-h-0 min-w-0">
      {/* Main Content */}
      <div className="flex min-h-0 min-w-0 flex-1 flex-col">
        {/* Table Header */}
        <div className="flex items-center justify-between border-b px-4 py-2">
          <div className="flex items-center gap-2">
            <h2 className="font-medium">{selectedTable.name}</h2>
            <span className="text-muted-foreground text-sm">
              ({totalRows.toLocaleString()} rows)
            </span>
            {selectedTable.type === 'view' && (
              <span className="bg-secondary text-muted-foreground flex items-center gap-1 rounded px-1.5 py-0.5 text-xs">
                <Eye className="h-3 w-3" />
                View
              </span>
            )}
          </div>

          <div className="flex items-center gap-2">
            {/* Add Row button */}
            {selectedTable.type !== 'view' && (
              <Button
                variant="outline"
                size="sm"
                onClick={handleAddRow}
                className="gap-2"
              >
                <Plus className="h-4 w-4" />
                Add Row
              </Button>
            )}

            {/* Changes indicator & preview button */}
            {changeCount > 0 && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowDiffPreview(true)}
                className="gap-2"
              >
                <FileText className="h-4 w-4" />
                {changeCount} pending {changeCount === 1 ? 'change' : 'changes'}
              </Button>
            )}
          </div>
        </div>

        {/* Data Grid */}
        <div className="min-h-0 min-w-0 flex-1">
          {isLoading ? (
            <div className="flex h-full items-center justify-center">
              <Loader2 className="text-muted-foreground h-8 w-8 animate-spin" />
            </div>
          ) : error ? (
            <div className="text-destructive flex h-full items-center justify-center">
              <p>{error.message}</p>
            </div>
          ) : (
            <DataTable
              ref={dataTableRef}
              columns={columns}
              data={displayRows}
              sort={sort}
              onSortChange={handleSortChange}
              grouping={grouping}
              onGroupingChange={setGrouping}
              editable={selectedTable.type !== 'view'}
              onCellChange={handleCellChange}
              onRowDelete={handleRowDelete}
              onRowInsert={handleAddRow}
              changes={changesMap}
              primaryKeyColumn={primaryKeyColumn}
              className="h-full"
              newRowId={newRowId}
              onNewRowFocused={handleNewRowFocused}
            />
          )}
        </div>

        {/* Pagination */}
        <div className="flex items-center justify-between border-t px-4 py-2">
          <div className="text-muted-foreground text-sm">
            Page {page} of {totalPages || 1}
          </div>
          <div className="flex items-center gap-1">
            <Button
              variant="outline"
              size="icon"
              className="h-8 w-8"
              onClick={() => handlePageChange(1)}
              disabled={page <= 1 || isLoading}
            >
              <ChevronsLeft className="h-4 w-4" />
            </Button>
            <Button
              variant="outline"
              size="icon"
              className="h-8 w-8"
              onClick={() => handlePageChange(page - 1)}
              disabled={page <= 1 || isLoading}
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <Button
              variant="outline"
              size="icon"
              className="h-8 w-8"
              onClick={() => handlePageChange(page + 1)}
              disabled={page >= totalPages || isLoading}
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
            <Button
              variant="outline"
              size="icon"
              className="h-8 w-8"
              onClick={() => handlePageChange(totalPages)}
              disabled={page >= totalPages || isLoading}
            >
              <ChevronsRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>

      {/* Diff Preview Panel */}
      {showDiffPreview && hasChanges && (
        <div className="w-96">
          <DiffPreview
            onClose={() => setShowDiffPreview(false)}
            onApplied={handleChangesApplied}
          />
        </div>
      )}
    </div>
  );
}
